### ISSUE TITLE
Node always apply delays 

### ISSUE THREAD

**Issue by michal-bartak** [tomgidden/node-red-contrib-timed-counter#8]
The node, after reaching requested message count doesn't send output immediatelly regardless the settings.
So, even scenario described in documentation (with mouse doble click) cannot work correctly.

**To reproduce:**
1. set the node to: time_limit 2s, fixed timeout: false, final message only: true, counter per topic: false
2. send two messages to input during a second
3. see, you need to wait 2 seconds for output

**Expected behaviour:**
output is sent immediately after reaching configured number of messages withing configured time window

![obrazek](https://user-images.githubusercontent.com/7868445/102725161-e2e50980-4314-11eb-8167-20aed50e02ed.png)

![obrazek](https://user-images.githubusercontent.com/7868445/102725143-c34de100-4314-11eb-8264-adac2813326c.png)

**Comment by tomgidden** [comment]
If I understand what you're doing correctly, this is intentional.

Each event resets the timer, which you've set at 2 seconds, so the node waits for 2 seconds after the last event to see if there are any more events coming.

If you set "fixed timeout" to true, it'll start the 2 second limit on the first event, and then report the number of clicks (including that one) 2 seconds after the _first_ event.   If "fixed timeout" is false, then each event will extend the timer for 2 more seconds.

Alternatively, you can change "final message only" to false, and then watch for a message with a count of 2.

For a mouse double-click scenario, I would set "final message only" to false, "fixed timeout" to false, and then filter for a message where count = 2:  that message would indicate a double click.

Having "final message only" set to true is so you can distinguish for, say, triple click from double click.

I hope that's of help!
